from . import kris_project_type
from . import kris_project_allocation_template
from . import kris_project
from . import exception_rule
from . import kris_project_installment
from . import kris_project_installment_allocation
from . import kris_project_receipt
from . import kris_project_receipt_allocation
from . import kris_project_allocation
from . import kris_project_dashboard
