{
    "name": "Budget Appropriation",
    "version": "16.0.1.2.1",
    "summary": "Budget Appropriation Management",
    "category": "KMITL/Budgeting",
    "author": "Aginix Technologies",
    "website": "https://github.com/aginix/kmitl",
    "depends": [
        "budget",
        "account_analytic_kmitl",
        "mail",
        "hr",
        "portal",
    ],
    "data": [
        "data/budget.account.xml",
        "data/budget_appropriation_f4_action.xml",
        "data/budget_appropriation_f4_pdf_report.xml",
        "data/budget_appropriation_f5_action.xml",
        "data/budget_appropriation_f5_pdf_report.xml",
        "data/budget_appropriation_sequence.xml",
        "security/ir.model.access.csv",
        "security/security.xml",
        "views/menus.xml",
        "views/budget_account_views.xml",
        "views/budget_appropriation_views.xml",
        "views/budget_move_views.xml",
        "views/templates.xml",
        "report/budget_appropriation_f4_report_templates.xml",
        "report/budget_appropriation_f5_report_templates.xml",
        "wizard/budget_appropriation_f5_print_wizard_views.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "budget_appropriation/static/src/**/*",
        ],
    },
    "auto_install": False,
    "application": False,
    "installable": True,
    "license": "AGPL-3",
}
