{
    "name": "Purchase Work Acceptance Kmitl",
    "version": "16.0.1.1.0",
    "summary": """ Purchase Work Acceptance Kmitl Summary """,
    "category": "KMITL",
    "author": "Aginix Technologies",
    "website": "https://github.com/aginix/kmitl",
    "depends": [
        'hr',
        'base_tier_validation_formula',
        'base_tier_validation_forward',
        'base_tier_validation_server_action',
        'base_tier_validation_comment',
        'purchase_work_acceptance_tier_validation',
        'purchase_work_acceptance_invoice_plan',
        'purchase_request_kmitl',
        'thai_date_utils',
        'l10n_th_amount_to_text',
        'purchase_kmitl',
        'purchase_order_received_qty_percent',
        'purchase_contract_kmitl',
    ],
    "data": [
        "security/ir.model.access.csv",
        "data/server_action.xml",
        "data/tier.definition.csv",
        "wizards/work_acceptance_committee_wizard.xml",
        "report/paperformat.xml",
        "report/report_work_acceptance.xml",
        "report/report_committee_acceptance.xml",
        "views/purchase_order_views.xml",
        "views/work_acceptance_views.xml",
        "views/purchase_invoice_plan_views.xml",
        "views/report_work_acceptance.xml",
        "views/report_committee_acceptance.xml",
    ],
    "post_init_hook": "post_init_hook",
    "installable": True,
    "auto_install": False,
    "license": "LGPL-3",
}
