# -*- coding: utf-8 -*-
{
    'name': 'Purchase Work Acceptance Kmitl',
    'version': '16.0.1.0.0',
    'summary': """ Purchase Work Acceptance Kmitl Summary """,
    "category": "KMITL",
    "author": "Aginix Technologies",
    "website": "https://github.com/aginix/kmitl",
    'depends': [
        'l10n_th_gov_work_acceptance',
        'base_tier_validation_comment',
        'thai_date_utils',
        'purchase_contract_kmitl',
        'l10n_th_amount_to_text',
        'purchase_kmitl',
    ],
    "data": [
        "data/server_action.xml",
        "data/tier.definition.csv",
        "report/paperformat.xml",
        "report/report_purchase_work_acceptance.xml",
        "report/report_wa_committee_acceptance.xml",
        "views/purchase_order_views.xml",
        "views/work_acceptance_views.xml",
        "views/purchase_work_acceptance_report.xml",
        "views/report_wa_committee_acceptance.xml",
    ],
    'installable': True,
    'auto_install': False,
    'license': 'LGPL-3',
}
