{
    "name": "Procurement Plan",
    "version": "16.0.1.0.0",
    "author": "Aginix Technologies",
    "website": "https://github.com/aginix/kmitl",
    "category": "KMITL",
    "depends": [
        "web",
        "budget",
        "l10n_th_gov_purchase_request",
    ],
    "data": [
        "data/account.analytic.plan.csv",
        "data/sequence.xml",
        "security/security.xml",
        "security/ir.model.access.csv",
        "views/analytic_views.xml",
        "views/procurement_plan_views.xml",
        "views/procurement_plan_menus.xml",
        "views/res_config_settings_views.xml",
    ],
    "assets": {},
    "application": True,
    "installable": True,
    "auto_install": False,
    "license": "LGPL-3",
}
