{
    "name": "Procurement Plan",
    "version": "16.0.1.2.0",
    "author": "Aginix Technologies",
    "website": "https://github.com/aginix/kmitl",
    "category": "KMITL",
    "depends": ["web", "budget"],
    "data": [
        "data/account.analytic.plan.csv",
        "data/sequence.xml",
        "data/budget_account_procurement_update.xml",
        "security/security.xml",
        "security/ir.model.access.csv",
        "views/budget_account_views.xml",
        "views/budget_commitment_views.xml",
        "views/budget_move_views.xml",
        "views/analytic_views.xml",
        "views/procurement_plan_views.xml",
        "views/procurement_plan_menus.xml",
        "views/res_config_settings_views.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "procurement_plan/static/src/components/**/*",
        ],
    },
    "application": True,
    "installable": True,
    "auto_install": False,
    "license": "LGPL-3",
}
