{
    "name": "KMITL Budgeting",
    "version": "16.0.1.5.3",
    "summary": """ KMITL Budgeting""",
    "category": "KMITL/Budgeting",
    "author": "Aginix Technologies",
    "website": "https://github.com/aginix/kmitl",
    "depends": [
        "account",
        "account_analytic_kmitl",
        "account_fiscal_year",
        "mail",
        "l10n_th_base_sequence",
    ],
    "data": [
        "data/budget_journal.xml",
        "data/budget.account.csv",
        "data/budget_account_rules.xml",
        "data/budget_sequence.xml",
        "data/budget_transfer_email_templates.xml",
        "security/security.xml",
        "security/ir.model.access.csv",
        "views/budget_account_views.xml",
        "views/budget_commitment_views.xml",
        "views/budget_journal_views.xml",
        "views/budget_move_views.xml",
        "views/budget_transfer_views.xml",
        "wizard/budget_commitment_line_wizard_views.xml",
        "wizard/budget_commitment_return_wizard_views.xml",
        "views/budget_menus.xml",
        "views/budget_dashboard_views.xml",
        "views/res_config_settings_views.xml",
    ],
    "assets": {
        "web.assets_backend": [
            # Apache ECharts (vendored) — attaches window.echarts for EChart.
            "budget/static/lib/echarts/echarts.min.js",
            "budget/static/src/dashboard/budget_dashboard.js",
            "budget/static/src/dashboard/budget_dashboard.xml",
            "budget/static/src/dashboard/budget_dashboard.scss",
            "budget/static/src/overview/echart.js",
            "budget/static/src/overview/budget_overview.js",
            "budget/static/src/overview/budget_overview.xml",
            "budget/static/src/overview/budget_overview.scss",
            "budget/static/src/reservation_picker/budget_reservation_picker.js",
            "budget/static/src/reservation_picker/budget_reservation_picker.xml",
            "budget/static/src/reservation_picker/budget_reservation_picker.scss",
        ],
    },
    "auto_install": False,
    "application": True,
    "license": "AGPL-3",
}
