{
    "name": "KMITL Budgeting",
    "version": "16.0.1.0.0",
    "summary": """ KMITL Budgeting""",
    "category": "KMITL/Budgeting",
    "author": "Aginix Technologies",
    "website": "https://github.com/aginix/kmitl",
    "depends": ["account", "account_analytic_kmitl", "account_fiscal_year", "mail", "l10n_th_base_sequence"],
    "data": [
        "data/budget_appropriation_preview_action.xml",
        "data/budget_journal.xml",
        "data/budget_move_data.xml",
        "data/budget.account.csv",
        "data/budget_paper_format.xml",
        "data/budget_sequence.xml",
        "security/ir.model.access.csv",
        "views/budget_account_views.xml",
        "views/budget_appropriation_views.xml",
        "views/budget_commitment_views.xml",
        "views/budget_journal_views.xml",
        "views/budget_move_views.xml",
        "views/budget_template_views.xml",
        "views/budget_menus.xml",
        "views/budget_report_views.xml",
        "views/budget_execution_status_report_views.xml",
        "views/budget_expenditure_report_views.xml",
        "views/budget_appropriation_overview_views.xml",
        "report/budget_appropriation_report_templates.xml",
        "report/budget_execution_status_report_templates.xml"
    ],
    "assets": {
        "web.assets_backend": ["budget/static/src/**/*"],
    },
    "auto_install": False,
    "application": True,
    "license": "AGPL-3",
}
