{
    "name": "Purchase Request KMITL",
    "version": "16.0.0.2.3",
    "summary": """ Purchase Request KMITL""",
    "category": "KMITL",
    "author": "Aginix Technologies",
    "website": "https://github.com/aginix/kmitl",
    "depends": [
        "hr",
        "hr_employee_name_detail_kmitl",
        "purchase_exception",
        "purchase_request_exception",
        "purchase_request_operating_unit",
        "purchase_request_price_tax_included",
        "account_fiscal_year",
        "purchase_order_kmitl",
        "purchase_operating_unit",
        "web_m2x_options",
        "web_attachment_document_type",
    ],
    "data": [
        "security/ir.model.access.csv",
        "security/purchase_request_security.xml",
        "data/purchase_exception.xml",
        "data/purchase_request_exception.xml",
        "data/purchase_request_line_exception.xml",
        "data/procurement_type.xml",
        "data/procurement_method.xml",
        "data/attachment_document_type.xml",
        "views/procurement_method_views.xml",
        "views/procurement_type_views.xml",
        "views/procurement_committee_views.xml",
        "wizards/purchase_request_cancel_wizard_views.xml",
        "wizards/purchase_request_return_wizard_views.xml",
        "views/purchase_request_views.xml",
        "views/purchase_order_line_views.xml",
        "views/purchase_order_views.xml",
        "wizards/purchase_request_line_make_purchase_order_views.xml",
    ],
    "installable": True,
    "auto_install": False,
    "license": "LGPL-3",
}
