{
    "name": "HR Employee Academic Standing Thailand",
    "version": "16.0.1.0.4",
    "summary": """ HR Employee Academic Standing Thailand Summary """,
    "description": "HR Employee Academic Standing Thailand",
    "author": "nopparuts, Aginix Technologies",
    "website": "https://github.com/aginix/kmitl-odoo",
    "category": "Human Resources",
    "depends": [
        "hr",
        "hr_employee_education_history",
        "hr_employee_role",
        "hr_employee_position_level",
    ],
    "data": [
        "data/data_hr_employee_academic_standing.xml",
        "data/data_hr_employee_profession.xml",
        "data/data_hr_employee_rank_nobility.xml",
        "data/data_resource_rank_agency.xml",
        "data/data_resource_rank.xml",
        "security/ir.model.access.csv",
        "views/resource_rank_agency_views.xml",
        "views/resource_rank_views.xml",
        "views/hr_employee_academic_standing_views.xml",
        "views/hr_employee_profession_views.xml",
        "views/hr_employee_rank_nobility_views.xml",
        "views/hr_employee_views.xml",
        "views/hr_views.xml",
    ],
    "application": True,
    "installable": True,
    "auto_install": False,
    "license": "LGPL-3",
}
