# License LGPL-3.0 or later (https://www.gnu.org/licenses/lgpl).

{
    "name": "Receipt KMITL",
    "version": "16.0.1.0.0",
    "category": "KMITL/Accounting",
    "license": "LGPL-3",
    "author": "KMITL",
    "summary": "Cash receipting with suspense reclassification for KMITL",
    "depends": [
        "account",
        "mail",
        "analytic",
        "account_analytic_kmitl",
    ],
    "data": [
        "security/security.xml",
        "security/ir.model.access.csv",
        "data/sequence.xml",
        "data/partner_walkin_data.xml",
        "data/receipt_type_data.xml",
        "wizard/receipt_cancel_wizard_views.xml",
        "wizard/allocation_create_wizard_views.xml",
        "wizard/receipt_refund_wizard_views.xml",
        "views/receipt_type_views.xml",
        "views/receipt_kmitl_views.xml",
        "views/cash_deposit_views.xml",
        "views/suspense_allocation_views.xml",
        "views/receipt_refund_views.xml",
        "views/account_journal_views.xml",
        "views/res_users_views.xml",
        "views/res_config_settings_views.xml",
        "views/menus.xml",
        "report/paperformat.xml",
        "report/receipt_kmitl_report.xml",
        "report/receipt_kmitl_action.xml",
    ],
    "installable": True,
    "application": True,
}
