{
    "name": "Purchase Request Approval",
    "version": "16.0.1.0.1",
    "author": "Aginix Technologies",
    "website": "https://github.com/aginix/kmitl",
    "category": "KMITL",
    "depends": [
        "purchase_request_kmitl",
        "purchase_request_price_tax_included",
        "purchase_request_sarabun",
        "purchase_request_activity_kmitl",
        "thai_date_utils",
        "portal",
        "purchase_request_egp",
    ],
    "data": [
        "data/purchase_request_approval_sequence.xml",
        "data/activity.xml",
        "data/sarabun_route_template_data.xml",
        "security/ir.model.access.csv",
        "security/purchase_request_approval.xml",
        "report/paperformat.xml",
        "views/portal_templates.xml",
        "views/purchase_order_views.xml",
        "views/purchase_request_approval_report.xml",
        "wizards/purchase_request_approval_cancel_wizard_views.xml",
        "wizards/purchase_request_approval_return_cancel_wizard_views.xml",
        "wizards/purchase_request_line_make_purchase_order_views.xml",
        "wizards/material_withdrawal_wizard_views.xml",
        "views/purchase_request_approval_views.xml",
        "views/purchase_request_views.xml",
        "report/report_purchase_request_approval.xml",
        "report/report_material_withdrawal.xml",
    ],
    "assets": {
        "web.assets_backend": ["purchase_request_approval/static/src/**/*"],
        "web.assets_frontend": [
            "purchase_request_approval/static/src/js/purchase_request_approval_portal_sidebar.js",
        ],
    },
    "installable": True,
    "auto_install": False,
    "license": "LGPL-3",
}
