# License LGPL-3.0 or later (https://www.gnu.org/licenses/lgpl).

{
    "name": "KMITL Finance",
    "version": "16.0.2.1.1",
    "category": "KMITL/Finance",
    "summary": "งานการเงิน KMITL: จ่ายเงิน, bank export, WHT, ทะเบียนคุมเช็ค, รายรับ/ใบเสร็จ",
    "license": "LGPL-3",
    "author": "KMITL",
    "website": "https://www.kmitl.ac.th",
    "depends": [
        "account",
        "account_kmitl",
        "accounting_kmitl",
        "accounting_kmitl_workflow",
        "account_fiscal_year_enhance",
        "budget",
        "l10n_th_bank_payment_export",
        "l10n_th_bank_payment_export_format",
        "thai_date_utils",
        "l10n_th_fonts",
        "l10n_th_amount_to_text",
        "l10n_th_account_wht_cert_form",
    ],
    "data": [
        "security/security.xml",
        "security/ir.model.access.csv",
        "data/kmitl_payment_type_data.xml",
        "data/cheque_register_sequence.xml",
        "views/kmitl_payment_type_views.xml",
        "views/account_payment_views.xml",
        "views/bank_payment_export_views.xml",
        "views/cheque_register_views.xml",
        "views/cheque_layout_views.xml",
        "views/account_journal_views.xml",
        "views/menuitem.xml",
        "report/paperformat.xml",
        "report/report_bank_payment_export_action.xml",
        "report/report_bank_payment_export.xml",
        "report/report_cheque_print.xml",
        "report/report_cheque_print_action.xml",
    ],
    "installable": True,
    "application": True,
}
