{
    "name": "KMITL Budgeting demo",
    "version": "16.0.1.0.1",
    "summary": """ KMITL Budgeting""",
    "category": "KMITL/Budgeting",
    "author": "nopparuts, Aginix Technologies",
    "website": "https://github.com/aginix/kmitl",
    "depends": ["account_analytic_kmitl", "budget", "kmitl_demo"],
    "data": [],
    "post_init_hook": "post_init_hook",
    "post_load_hook": "post_load_hook",
    "uninstall_hook": "uninstall_hook",
    "auto_install": False,
    "application": True,
    "license": "AGPL-3",
}
