{
    "name": "HR Employee Education History",
    "version": "16.0.1.1.2",
    "category": "Human Resources",
    "website": "https://github.com/aginix/kmitl-odoo",
    "author": "Nonpawit, Aginix Technologies",
    "maintainers": ["n3n", "nopparuts"],
    "license": "AGPL-3",
    "installable": True,
    "application": False,
    "summary": "Allows storing information about employee's education history",
    "description": "Allows storing information about employee's education history",
    "depends": ["hr"],
    "data": [
        "data/data_resource_education_level.xml",
        "security/ir.model.access.csv",
        "views/hr_employee.xml",
        "views/hr_employee_education_history.xml",
        "views/resource_university.xml",
        "views/resource_education_level.xml",
        "views/resource_education_faculty.xml",
        "views/resource_education_department.xml",
        "views/resource_education_program.xml",
        "views/hr_views.xml",
    ],
}
