{
    "name": "Aginix Approval",
    "version": "16.0.1.0.1",
    "category": "Accounting",
    "author": "Aginix Technologies",
    "website": "https://github.com/aginix/kmitl",
    "license": "LGPL-3",
    "depends": ["account", "hr", "budget_product", "budget", "base_exception"],
    "data": [
        "security/security.xml",
        "security/ir.model.access.csv",
        "wizard/approval_request_exception_confirm_view.xml",
        "wizard/update_actual_amount_wizard_views.xml",
        "views/approval_category_views.xml",
        "views/approval_category_group_views.xml",
        "views/approval_request_views.xml",
        "views/approval_menus.xml",
        "data/approval_sequence.xml",
        "data/approval_category_group.xml",
        "data/approval_category.xml",
    ],
    "license": "LGPL-3",
}
