{
    "name": "Aginix Approval",
    "version": "16.0.1.1.0",
    "category": "Accounting",
    "author": "Aginix Technologies",
    "website": "https://github.com/aginix/kmitl",
    "license": "LGPL-3",
    "depends": [
        "account",
        "hr",
        "budget_product",
        "budget",
        "base_exception",
        "account_fiscal_year_enhance",
        "l10n_th_amount_to_text",
        "partner_type_aginix",
        "hr_employee_name_detail_kmitl",
    ],
    "data": [
        "security/security.xml",
        "security/ir.model.access.csv",
        "wizard/approval_request_exception_confirm_view.xml",
        "wizard/pull_back_confirm_views.xml",
        "reports/paperformat_approval_request.xml",
        "reports/report_disbursement_voucher.xml",
        "views/approval_category_views.xml",
        "views/approval_category_group_views.xml",
        "views/approval_request_views.xml",
        "views/approval_menus.xml",
        "data/approval_sequence.xml",
        "data/approval_category_group.xml",
        "data/approval_category.xml",
        "reports/report_approval_request.xml",
    ],
    "license": "LGPL-3",
}
