{
    "name": "Advance Payment (สัญญายืมเงิน)",
    "version": "16.0.2.0.0",
    "author": "Aginix Technologies",
    "website": "https://github.com/aginix/kmitl",
    "category": "KMITL",
    "depends": [
        "mail",
        "l10n_th_base_sequence",
        "hr",
        "purchase_request",
        "account_payment_kmitl",
        "base_exception",
    ],
    "data": [
        "security/ir.model.access.csv",
        "data/advance_payment_exception_data.xml",
        "data/advance_payment_sequence.xml",
        "data/advance_payment_loan_type_data.xml",
        "data/advance_payment_bank_data.xml",
        "data/kmitl_payment_type_data.xml",
        "wizards/advance_payment_exception_confirm.xml",
        "wizards/advance_payment_usage_wizard_views.xml",
        "wizards/advance_payment_return_wizard_views.xml",
        "views/advance_payment_loan_type_views.xml",
        "views/advance_payment_bank_views.xml",
        "views/advance_payment_usage_line_views.xml",
        "views/advance_payment_views.xml",
        "views/account_payment_views.xml",
        "views/exception_rule_views.xml",
        "views/advance_payment_menus.xml",
    ],
    "application": True,
    "installable": True,
    "auto_install": False,
    "license": "LGPL-3",
}
