# -*- coding: utf-8 -*-
{
    'name': 'KMITL Depends Dev',
    'version': '16.0.1.0.0',
    'summary': """ KMITL Depends Dev Summary """,
    "category": "KMITL",
    "author": "Aginix Technologies",
    "website": "https://github.com/aginix/kmitl",
    'depends': ['kmitl_demo', 'budget_demo', 'budget_appropriation_demo', 'procurement_plan_demo', 'account_analytic_ux_kmitl',
                'account_asset_kmitl', 'account_asset_number_kmitl', 'account_asset_operating_unit_access_all',
                'account_asset_batch', 'account_asset_subcomponent_kmitl',
                'account_fiscal_year_all_user', 'account_fiscal_year_enhance',
                'disbursement', 'accounting_kmitl',
                'analytic_operating_unit_tree', 'base_tier_validation_comment', 'budget_account_mass_edit',
                'budget_analytic_account', 'budget_appropriation_operating_unit',
                'budget_appropriation_report',
                'budget_operating_unit_access_all', 'budget_report',
                'hr_department_code_tracking', 'stock_picking_kmitl', 'stock_request_kmitl_tier_validation', 'i18n_th_stock_inventory',
                'i18n_th_tier_validation', 'l10n_th_bank_payment_export_format', 'operating_unit_kmitl', 'partner_type_aginix',
                'partner_vat_required', 'stock_scrap_attachment', 'stock_scrap_hide_location_id', 'stock_scrap_origin_readonly_done',
                'purchase_order_hide_create_bill_button', 'purchase_order_procurement_committee',
                'purchase_order_received_qty_percent', 'purchase_order_report_kmitl', 'purchase_request_activity_kmitl',
                'purchase_request_approval_disbursement', 'purchase_request_approval_attach_existing_attachments',
                'purchase_request_operating_unit_access_all',
                'purchase_sequence_kmitl', 'purchase_request_sarabun', 'purchase_request_sequence_kmitl',
                'purchase_request_kmitl', 'purchase_work_acceptance_invoice_plan_deliverables', 'purchase_work_acceptance_invoice_plan_usability',
                'purchase_work_acceptance_kmitl', 'purchase_work_acceptance_portal',
                'stock_inventory_department', 'stock_inventory_kmitl', 'stock_inventory_restriction',
                'stock_scrap_reason_text', 'stock_scrap_responsible_user', 'thai_date_utils', 'web_kmitl', 'web_widget_helper_text', 'web_theme_classic_extended', 'kmitl_project',
                'hr_department_short_name', 'hr_department_tracking', 'purchase_invoice_plan_kmitl',
                'purchase_guarantee_account_payment', 'purchase_guarantee_bid_guarantee_kmitl',
                'purchase_guarantee_kmitl',
                'purchase_manual_delivery_security', 'purchase_manual_delivery_work_acceptance',
                'purchase_operating_unit_access_all', 'purchase_order_disbursement',
                'purchase_order_disbursement_budget', 'web_responsive',
                'advance_payment_disbursement', 'agx_approval_disbursement',
                'disbursement_accounting_kmitl', 'disbursement_finance_kmitl',
                'disbursement_sarabun', 'purchase_order_disbursement_auto_submit',
                'purchase_request_approval_disbursement_budget',
                'purchase_work_acceptance_disbursement', 'web_chatter_position'],
    'data': [

    ],
    'installable': True,
    'auto_install': False,
    'license': 'LGPL-3',
}
