{
    "name": "KMITL HR API",
    "version": "16.0.1.6.12",
    "category": "Human Resources",
    "website": "https://github.com/aginix/kmitl-odoo",
    "author": "nopparuts, Aginix Technologies",
    "maintainers": ["nopparuts", "coreichamp"],
    "license": "AGPL-3",
    "installable": True,
    "application": False,
    "summary": "Provide api infomation of employees.",
    "depends": [
        "hr",
        "auth_api_key",
        "kmitl_hr_employee_service",
        "hr_employee_code",
        "hr_employee_management_record",
        "kmitl_hr_employee_full_name",
        "aginix_hrms_base",
        "hr_employee_position_level",
        "hr_employee_role",
        "kmitl_hr_welfare_type",
        "hr_employee_digitized_signature",
        "kmitl_hr_employee_type",
        "kmitl_hr_employee_departure",
        "hr_employee_relative",
        "kmitl_hr_employee_contract",
        "hr_employee_movement",
        "hr_employee_address_home_form_inline",
        "hr_employee_current_home_form_inline",
        "hr_employee_extra_fields",
        "hr_employee_kmitl_kid",
    ],
}
