{
    "name": "KMITL HR API Base",
    "version": "16.0.1.0.9",
    "summary": """ KMITL HR API Base Summary """,
    "author": "nopparuts, Aginix Technologies",
    "website": "https://github.com/aginix/kmitl-odoo",
    "category": "Human Resources",
    "depends": [
        "hr",
        "hr_employee_code",
        "kmitl_hr_employee_full_name",
        "kmitl_hr_employee_type",
        "hr_employee_role",
        "hr_employee_position_level",
        "hr_employee_academic_department",
        "hr_employee_extra_fields",
        "hr_employee_kmitl_kid",
        "hr_employee_extra_fields",
        "hr_employee_academic_standing_thailand",
        "hr_employee_education_history",
    ],
    "application": True,
    "installable": True,
    "auto_install": False,
    "license": "LGPL-3",
}
