{
    "name": "Budget Appropriation Summary",
    "version": "16.0.1.0.9",
    "summary": "Compilation and master summary for budget appropriations",
    "category": "KMITL/Budgeting",
    "author": "Aginix Technologies",
    "website": "https://github.com/aginix/kmitl",
    "depends": ["budget_appropriation", "web", "l10n_th_fonts"],
    "data": [
        "data/dashboard_action.xml",
        "data/paper_format.xml",
        "security/ir.model.access.csv",
        "views/budget_appropriation_compilation_views.xml",
        "views/budget_appropriation_line_views.xml",
        "views/budget_appropriation_views.xml",
        "views/budget_appropriation_master_summary_views.xml",
        "views/menu.xml",
        "views/wizard_master_summary_done_views.xml",
        "wizard/compilation_f5_print_wizard_views.xml",
        "wizard/master_summary_print_wizard_views.xml",
        "report/report_common.xml",
        "report/report_compilation_f23w.xml",
        "report/report_compilation_f4.xml",
        "report/report_compilation_f5.xml",
        "report/report_compilation_book.xml",
        "report/report_f10w_expense.xml",
        "report/report_f11w_expense.xml",
        "report/report_f2_revenue.xml",
        "report/report_f3w_f6w_revenue.xml",
        "report/report_f4p_revenue.xml",
        "report/report_f4w_revenue.xml",
        "report/report_f5p_expense.xml",
        "report/report_f5w_expense.xml",
        "report/report_f7w_expense.xml",
        "report/report_f8w_expense.xml",
        "report/report_f9w_expense.xml",
        "report/report_master_summary.xml"
    ],
    "assets": {
        "web.assets_backend": [
            "budget_appropriation_summary/static/src/**/*",
        ],
    },
    "auto_install": False,
    "application": False,
    "installable": True,
    "license": "AGPL-3",
}
