# -*- coding: utf-8 -*-
{
    "name": "KMITL Project",
    "version": "16.0.1.0.0",
    "author": "",
    "website": "",
    "category": "",
    "depends": ["web", "hr", "account_fiscal_year", "budget", "project", "base_exception"],
    "data": [
        "data/account.analytic.plan.csv",
        "data/project.evaluation.csv",
        "data/project.strategic.plan.csv",
        "data/project.fight.csv",
        "data/project.global.index.csv",
        "data/project.impact.csv",
        "data/project.methodology.csv",
        "data/kmitl_project_exception_data.xml",
        "security/ir.model.access.csv",
        "views/menu_views.xml",
        "views/kmitl_project_views.xml",
        "views/project_evaluation_views.xml",
        "views/project_fight_views.xml",
        "views/project_global_index_views.xml",
        "views/project_impact_views.xml",
        "views/project_methodology_views.xml",
        "views/project_strategic_plan_views.xml",
        "views/portal_templates.xml"
    ],
    "assets": {
        "web.assets_backend": ["kmitl_project/static/src/**/*"],
    },
    "application": True,
    "installable": True,
    "auto_install": False,
    "license": "LGPL-3",
}
