# -*- coding: utf-8 -*-
{
    "name": "KMITL Project",
    "version": "16.0.1.3.0",
    "category": "Project",
    "author": "Aginix Technologies",
    "website": "https://github.com/aginix/kmitl",
    "depends": [
        "web",
        "hr",
        "account_fiscal_year",
        "budget",
        "project",
        "base_exception",
        "l10n_th_fonts",
        "operating_unit",
        "portal",
        "account_analytic_kmitl",
    ],
    "data": [
        "report/paperformat.xml",
        "report/report_kmitl_project.xml",
        "data/account.analytic.plan.csv",
        "data/kmitl_project_exception_data.xml",
        "data/project.evaluation.csv",
        "data/project.fight.csv",
        "data/project.global.index.csv",
        "data/project.impact.csv",
        "data/project.methodology.csv",
        "data/project.strategic.plan.csv",
        "data/budget_account_project_update.xml",
        "security/security.xml",
        "security/ir.model.access.csv",
        "views/menu_views.xml",
        "views/kmitl_project_views.xml",
        "views/budget_account_views.xml",
        "views/portal_templates.xml",
        "views/portal_dashboard_templates.xml",
        "views/project_evaluation_views.xml",
        "views/project_fight_views.xml",
        "views/project_global_index_views.xml",
        "views/project_impact_views.xml",
        "views/project_methodology_views.xml",
        "views/project_strategic_plan_views.xml",
        "views/kmitl_project_report.xml",
    ],
    "assets": {
        "web.assets_backend": ["kmitl_project/static/src/components/**/*"],
        "web.assets_frontend": [
            "kmitl_project/static/src/portal/scss/dashboard.scss",
            "kmitl_project/static/src/portal/js/dashboard.js",
        ],
    },
    "application": True,
    "installable": True,
    "auto_install": False,
    "license": "LGPL-3",
}
