# Part of Odoo. See LICENSE file for full copyright and licensing details.

{
    "name": "KMITL Demo",
    "version": "16.0.0.0.0",
    "category": "KMITL",
    "author": "Aginix Technologies",
    "website": "https://github.com/aginix/kmitl",
    "depends": [
        "base",
        "account_kmitl",
        "hr_department_code",
        "account_fiscal_year",
        "account_analytic_kmitl",
        "hr_department_short_name",
        "hr_department_operating_unit",
        "purchase_request_kmitl",
        "purchase_request_exception",
        "purchase_request_tender_kmitl",
        "purchase_request_egp",
        "purchase_request_department",
        "purchase_request_budget",
        "purchase_request_price_tax_included",
        "purchase_request_approval_kmitl",
        "purchase_request_approval",
        "purchase_request_sarabun",
        "operating_unit_kmitl",
        "analytic_operating_unit",
        "account_analytic_kmitl",
        "disbursement",
        "purchase_request_approval_work_acceptance",
        "agx_approval",
        "agx_approval_disbursement",
    ],
    "data": [
        "data/company.xml",
        "data/hr.department.csv",
        "data/res.users.xml",
        "data/hr.employee.xml",
        "data/res.partner.xml",
        "data/res.bank.xml",
        "data/res.partner.bank.xml",
        "data/account.fiscal.year.csv",
        "data/ir_config_parameter.xml",
        "data/purchase.request.xml",
        "data/purchase.request.dashboard.demo.xml",
        "data/approval.request.xml",
        "data/account.analytic.account.xml",
        "data/res.users.role.xml",
    ],
    "post_init_hook": "post_init",
    "uninstall_hook": "uninstall_hook",
    "application": False,
    "installable": True,
    "auto_install": False,
    "license": "LGPL-3",
}
