{
    "name": "HR Recruitment KMITL",
    "version": "16.0.1.0.0",
    "summary": "Custom theme and pages for KMITL recruitment website",
    "author": "Aginix Technologies, KMITL",
    "category": "Website",
    "depends": [
        "website",
        "website_hr_recruitment",
        "theme_kmitl",
        "base_location",
        "partner_firstname",
        "partner_middlename",
        "hr_employee_academic_standing_thailand",
        "hr_employee_education_history",
        "hr_employee_decoration",
        "hr_employee_relative",
        "kmitl_hr_employee_full_name",
    ],
    "data": [
        "security/ir.model.access.csv",
        "security/security.xml",
        "data/server_actions.xml",
        "data/website_data.xml",
        "views/snippets/s_benefit_card.xml",
        "views/snippets/snippets.xml",
        "views/shared_components.xml",
        "views/hr_job_views.xml",
        "views/website_templates.xml",
        "views/portal_profile_views.xml",
        "views/res_partner_views.xml",
        "views/profile_templates.xml",
        "views/portal_templates.xml",
        "views/hr_applicant_views.xml",
        "views/hr_onboarding_views.xml",
        "views/website_hr_recruitment_defaults.xml",
        "views/website_hr_recruitment_index.xml",
        "views/website_hr_recruitment_detail.xml",
        "views/website_hr_recruitment_apply_tabs.xml",
        "views/website_hr_recruitment_apply.xml",
        "views/portal_application_detail_tabs.xml",
        "views/portal_onboarding_templates.xml",
        "views/portal_onboarding_tabs.xml",
    ],
    "assets": {
        "web.assets_frontend": [
            "hr_recruitment_kmitl/static/src/scss/theme.scss",
            "hr_recruitment_kmitl/static/src/js/profile_page.js",
            "hr_recruitment_kmitl/static/src/js/apply_page.js",
            "hr_recruitment_kmitl/static/src/js/onboarding_family.js",
        ],
        "web._assets_frontend_helpers": [
            (
                "prepend",
                "hr_recruitment_kmitl/static/src/scss/bootstrap_overridden.scss",
            ),
        ],
        "website.assets_editor": [
            "hr_recruitment_kmitl/static/src/js/form_editor.js",
        ],
    },
    "application": False,
    "installable": True,
    "auto_install": False,
    "post_init_hook": "create_job_website_and_menu",
    "license": "LGPL-3",
}
